name = "legalnest"
compatibility_date = "2023-09-04"

# Tell wrangler where your static files are
[site]
bucket = "./dist"

# Basic configuration for a Pages project
[build]
command = "npm run build"
output_dir = "dist"

# Configure custom routes for SPA
[routes]
pattern = "/*"
script = "worker.js"

# Set up caching rules through headers
[headers]
  [headers."/*"]
    Cache-Control = "public, max-age=86400"
  
  [headers."/*.js"]
    Cache-Control = "public, max-age=3600"
  
  [headers."/*.css"]
    Cache-Control = "public, max-age=3600"
  
  [headers."/*.html"]
    Cache-Control = "public, max-age=3600"
  
  [headers."/*.{jpg,jpeg,png,gif,webp,svg}"]
    Cache-Control = "public, max-age=604800"