name = "legalnest"
compatibility_date = "2023-09-04"

[site]
bucket = "./dist"

# Handle SPA routing with a custom route
[[rules]]
type = "NavigationRoute"
route = "/*"
strategy = "html-fallback"

# Configure cache behavior for assets
[[rules]]
type = "CacheEverythingRule"
cacheTtl = 86400 # 1 day

# Set specific cache rules for file types
[[rules]]
type = "CacheRule"
globs = ["**/*.{js,css,html}"]
cacheTtl = 3600 # 1 hour

[[rules]]
type = "CacheRule"
globs = ["**/*.{jpg,jpeg,png,gif,webp,svg}"]
cacheTtl = 604800 # 7 days